import aiosmtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from app.core.config import settings

def build_email_html(meeting_data: dict) -> str:
    actions_html = "".join(
        f"<tr><td>{a['task']}</td><td><strong>{a['owner']}</strong></td>"
        f"<td>{a.get('due','TBD')}</td><td>{a.get('priority','MEDIUM')}</td></tr>"
        for a in meeting_data.get("action_items", [])
    )
    decisions_html = "".join(f"<li>{d}</li>" for d in meeting_data.get("decisions", []))
    return f"""
    <html><body style='font-family:sans-serif;max-width:700px;margin:auto'>
    <h2>🎤 Meeting Summary</h2>
    <p>{meeting_data.get('summary','')}</p>
    <h3>Action Items</h3>
    <table border='1' cellpadding='8' style='border-collapse:collapse;width:100%'>
    <tr><th>Task</th><th>Owner</th><th>Due</th><th>Priority</th></tr>
    {actions_html}
    </table>
    <h3>Decisions Made</h3><ul>{decisions_html}</ul>
    <p style='color:#888;font-size:12px'>Generated by SmartMeet AI</p>
    </body></html>
    """

async def send_summary_email(to_addresses: list[str], meeting_data: dict, subject: str = "Meeting Summary"):
    if not settings.smtp_user:
        return  # Email not configured, skip silently
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = settings.smtp_user
    msg["To"] = ", ".join(to_addresses)
    msg.attach(MIMEText(build_email_html(meeting_data), "html"))
    await aiosmtplib.send(
        msg,
        hostname=settings.smtp_host,
        port=settings.smtp_port,
        username=settings.smtp_user,
        password=settings.smtp_password,
        start_tls=True,
    )
